# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moshpit < Formula
  desc "A terminal-based SSH/Mosh manager with protocol flexibility and roaming connection support"
  homepage "https://github.com/taylorbanks/moshpit"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/taylorbanks/moshpit/releases/download/v0.3.0/moshpit_Darwin_x86_64.tar.gz"
      sha256 "ceb0ce7caf2e41f4198ed4d20bfffc2e9e25ff499c9c7192a8b4845004e62fd9"

      define_method(:install) do
        bin.install "moshpit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/taylorbanks/moshpit/releases/download/v0.3.0/moshpit_Darwin_arm64.tar.gz"
      sha256 "1d994f2b3ffce5c395317e769fde14b7c139ea7dde5d4a375532546d36ef7903"

      define_method(:install) do
        bin.install "moshpit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/taylorbanks/moshpit/releases/download/v0.3.0/moshpit_Linux_x86_64.tar.gz"
      sha256 "5aaba1d01145c1d80807d62b88bb6242eadc6dc77896f7cee954296fcb42fb5c"
      define_method(:install) do
        bin.install "moshpit"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/taylorbanks/moshpit/releases/download/v0.3.0/moshpit_Linux_armv6.tar.gz"
      sha256 "6d540f7975c8c85858f6f6d280b3d244e6d682213d0d107d4dc3fd5640f8ab85"
      define_method(:install) do
        bin.install "moshpit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/taylorbanks/moshpit/releases/download/v0.3.0/moshpit_Linux_arm64.tar.gz"
      sha256 "f8c04c6835eaf00e57a25091bec20e223ba92d140276a890cf4c3f69837bff9d"
      define_method(:install) do
        bin.install "moshpit"
      end
    end
  end

  test do
    system "#{bin}/moshpit", "--version"
  end
end
