# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moshpit < Formula
  desc "A terminal-based SSH/Mosh manager with protocol flexibility and roaming connection support"
  homepage "https://github.com/taylorbanks/moshpit"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/taylorbanks/moshpit/releases/download/v0.1.0/moshpit_Darwin_x86_64.tar.gz"
      sha256 "e688794b98efd3501000005beb19d07434522ddffcfe71ed8c3acf2ea76a295e"

      define_method(:install) do
        bin.install "moshpit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/taylorbanks/moshpit/releases/download/v0.1.0/moshpit_Darwin_arm64.tar.gz"
      sha256 "4f4c870f9ce4231d3621856d9876cb6e0a4550134b1addf1ec467c81bd1999f5"

      define_method(:install) do
        bin.install "moshpit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/taylorbanks/moshpit/releases/download/v0.1.0/moshpit_Linux_x86_64.tar.gz"
      sha256 "0ab663cd50f6650b05ca6a019a02280d386026fa4c0678b071899beadd257fa2"
      define_method(:install) do
        bin.install "moshpit"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/taylorbanks/moshpit/releases/download/v0.1.0/moshpit_Linux_armv6.tar.gz"
      sha256 "68c5e27b526a750fddac00b3cd2fcba971d128c3a679745ac193c150b998d9b6"
      define_method(:install) do
        bin.install "moshpit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/taylorbanks/moshpit/releases/download/v0.1.0/moshpit_Linux_arm64.tar.gz"
      sha256 "d52933f8799e095732903fc9482dc3c123abad0b9dd5d5619fe4e90e75685348"
      define_method(:install) do
        bin.install "moshpit"
      end
    end
  end

  test do
    system "#{bin}/moshpit", "--version"
  end
end
