# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moshpit < Formula
  desc "A terminal-based SSH/Mosh manager with protocol flexibility and roaming connection support"
  homepage "https://github.com/taylorbanks/moshpit"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/taylorbanks/moshpit/releases/download/v0.2.0/moshpit_Darwin_x86_64.tar.gz"
      sha256 "9147fdbaf892c06deac4a18e3f7eed84037a708f0543ce892f9df8caa1ebb3dd"

      define_method(:install) do
        bin.install "moshpit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/taylorbanks/moshpit/releases/download/v0.2.0/moshpit_Darwin_arm64.tar.gz"
      sha256 "e5787efd756e8f3d0105f3d8b8a9152df572f09777a804c173cd1031827d1235"

      define_method(:install) do
        bin.install "moshpit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/taylorbanks/moshpit/releases/download/v0.2.0/moshpit_Linux_x86_64.tar.gz"
      sha256 "af4c986921ecdb6266b36b0ae6162051548b67fe9ea27c858d55e984622ef265"
      define_method(:install) do
        bin.install "moshpit"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/taylorbanks/moshpit/releases/download/v0.2.0/moshpit_Linux_armv6.tar.gz"
      sha256 "9b0528541a9b972986ccc65b9df3a85feaae8368f138aec4903faa4ac6ed0df2"
      define_method(:install) do
        bin.install "moshpit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/taylorbanks/moshpit/releases/download/v0.2.0/moshpit_Linux_arm64.tar.gz"
      sha256 "6bf1b12787ceaf658eab15a8c9b3be017febd48794ef1f9094a7989b666a7342"
      define_method(:install) do
        bin.install "moshpit"
      end
    end
  end

  test do
    system "#{bin}/moshpit", "--version"
  end
end
